[add]admin系機能
yosnak13/booboobook pull request #10
Opened 2021-09-20 06:50 UTC by 1994reka3

# やったこと
- deviseのadmin controller,admin views作成
- admins/users controller作成、indexアクション定義
- routeにnamespaceでadmins側のルートを定義

2021-09-22 15:07 UTC, yosnak13 requested changes
3点確認があるので、コメントの確認お願いします。仕様をどのようにすればいいのか不明な部分があると思いますのでその点は相談して決めましょうか！

2021-09-22 15:07 UTC, yosnak13 commented on db/seeds.rb
> +
現状は各自でrails db:migrate:reset + rails db:seedでadmin作る感じですかね？

2021-09-22 15:07 UTC, yosnak13 commented on app/views/layouts/_header.html.erb
> +          <% elsif admin_signed_in? %>  <%# 管理者がログインした場合 %>
adminでログインした後、直後URLにuser/sign_inを手打ちしてuserログインすると、adminをログアウトできなくなるバグが発生しちゃってますね、、、。

2021-09-23 05:34 UTC, 1994reka3 commented on app/controllers/application_controller.rb
> +
前に開発した際にApricationControllerに記載していたので流用してそのままやってしまいました。
しかしおっしゃるとおりAdminのSessionsControllerに書いたほうが適切ですね。
ご指摘ありがとうございます！修正します。

2021-09-23 05:36 UTC, 1994reka3 commented on db/seeds.rb
> +
管理者でログインしたかったので上記でひとまず作成しました。
その辺今度ご相談させてください。

2021-09-23 05:37 UTC, 1994reka3 commented on app/views/layouts/_header.html.erb
> +          <% elsif admin_signed_in? %>  <%# 管理者がログインした場合 %>
ありがとうございます。気づきませんでした。
対応策が今の所思い浮かばないのですが色々試行錯誤してみます。
後でご相談させていただきます。

2021-09-23 07:47 UTC, yosnak13 reviewed
OK

2021-09-23 07:47 UTC, merged