本棚のページのデザインを編集しました(index.html.erbとbooks.scss)
yosnak13/booboobook pull request #52
Opened 2022-02-13 06:42 UTC by Tomoaki0726

## 概要
本棚ページのデザイン編集を行いました。
アイコンやテキストをレスポンシブにしています。

##未完成の部分
登録している本の一覧ページのリンク先の挿入は出来ていません。

お忙しい中と存じますが、ご確認をよろしくお願い致します。

2022-02-13 09:32 UTC, yosnak13 requested changes
scss、html.erb双方にいくつか修正依頼を出しましたので、確認と修正をお願いします。

2022-02-13 09:32 UTC, yosnak13 commented on app/assets/stylesheets/books.scss
> +	color: #fff;
ここのコード全般的に言えることになるのですが、インデントは半角スペース2個にできますかね？
他のコードを見ていただくとわかりやすいのですが、インデントが入ると半透明で「・・」と表示されます。
タブ入力（→と表示されてしまう）になっちゃってるんですよね、、、。
おそらくVScodeの設定で治るかと。

2022-02-13 09:32 UTC, yosnak13 commented on app/assets/stylesheets/books.scss
> +//ボタンの上にポインタを持ってきたり、クリックしたりした時の背景色とテキストの色
36行目から61行目、71行目から86行目はおそらく他のscssファイルで記載されている内容と重複するので、不要のかなと。
対象行をコメントアウトしてテストしましたが、問題なく動くようです。
Railsのアセットパイプラインという機能で、他のScssファイルに記載されているコードも読み込むという便利？な機能です。
これはRailsの特徴なので存じなくても仕方ない部分ですので気にしないでくださいね！

2022-02-13 09:32 UTC, yosnak13 commented on app/views/books/index.html.erb
> +          <nav aria-label="Page navigation example">
ここって修正いただいた箇所のうちの一つでしたでしょうか？

2022-02-13 12:15 UTC, Tomoaki0726 commented on app/views/books/index.html.erb
> +          <nav aria-label="Page navigation example">
緑のラインの部分でしょうか？
この部分は修正した記憶がないです。
赤いラインの部分は色々いじった関係で触ったと思います。

2022-02-13 12:38 UTC, Tomoaki0726 commented on app/assets/stylesheets/books.scss
> +//ボタンの上にポインタを持ってきたり、クリックしたりした時の背景色とテキストの色
36行目から61行目確認しました。
削除致します。

もうひとつは、79行目から91行目でしょうか？
私が触った時にずれてしまったかもです。
36行目から61行目と同様の記述を削除で、問題なければ削除いたします！

2022-02-13 12:47 UTC, Tomoaki0726 commented on app/assets/stylesheets/books.scss
> +//ボタンの上にポインタを持ってきたり、クリックしたりした時の背景色とテキストの色
<img width="460" alt="スクリーンショット 2022-02-13 21 46 32" src="https://user-images.githubusercontent.com/71681730/153753747-4369aa59-16e5-4096-b34f-4c8545bbe95c.png">

2022-02-27 11:52 UTC, yosnak13 reviewed
ok

2022-02-27 11:52 UTC, merged